version: "3.4"

services:
  espwebsite:
    image: espwebsite
    privileged: true
    network_mode: host
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5000:5000
